(include_subdirs qualified)

(coq.theory
 (name New)
 (modules
  :standard
  \
  experiments.checker
  experiments.congruence_test
  experiments.store
  experiments.type
  experiments.unsound)
 (theories
  Stdlib
  Ltac2
  stdpp
  iris
  iris.heap_lang
  coqutil
  RecordUpdate
  iris_named_props
  Perennial))
