(include_subdirs qualified)

(coq.theory
 (name New)
 (modules
  :standard
  \
  golang.theory.proofmode_tests
  experiments.lang
  experiments.congruence_test)
 (theories
  Stdlib
  Ltac2
  stdpp
  iris
  coqutil
  RecordUpdate
  iris_named_props
  Perennial
  Perennial.program_proof ;; TODO: only due to preludes
  ))
