name: CI

on:
  push:
  # allow running action manually.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python dependencies
        run: |
          sudo apt-get install -y python3 python3-pandas sqlite3
      - name: Install Coq
        run: |
          ./etc/install-deps.sh
          ./etc/install-ocaml.sh
          ./etc/install-dune.sh
          ./etc/install-coq.sh
      - name: Build
        run: |
          make -j4 -k src/Helpers/List.vo
